In [1]:
import pandas as pd
import os
import pathlib
import glob
import numpy as np

In [24]:
leor = pd.read_excel('../IMC_data/ExtraDocs/imc_metadata.xlsx',dtype={'acquisition_raw_id':str})

In [27]:
leor

,leap_id,run_id,is_core,acquisition_id,acquisition_raw_id,panorama_source_file,panorama_raw_id,large_panorama_raw_id,Unnamed: 8
0,Leap001,NaN,1,001,8,Leap001/raw/Leap001.mcd,3,NaN,NaN
1,Leap001,NaN,1,002,9,Leap001/raw/Leap001.mcd,3,NaN,NaN
2,Leap001,NaN,1,003,10,Leap001/raw/Leap001.mcd,3,NaN,NaN
3,Leap002,NaN,0,002,7,Leap002/raw/Leap002.mcd,2,NaN,NaN
4,Leap002,NaN,0,003,6,Leap002/raw/Leap002.mcd,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...
652,Leap096,NaN,0,007,7,Leap096/raw/Leap096.mcd,8,10.0,NaN
653,Leap096,NaN,0,008,8,Leap096/raw/Leap096.mcd,8,10.0,NaN
654,Leap096,NaN,0,009,9,Leap096/raw/Leap096.mcd,7,10.0,NaN
655,Leap096,NaN,0,010,10,Leap096/raw/Leap096.mcd,7,10.0,NaN
656,Leap096,NaN,0,011,11,Leap096/raw/Leap096.mcd,8,10.0,NaN

In [55]:
ours = glob.glob('../split_channels_nohpf/*')
ours = pd.Series(ours).map(lambda path: pathlib.Path(path).parts[-1])
ours = pd.DataFrame(ours,columns = ['full_name'])
ours['acquisition_ID'] = ours.full_name.str.split('_',n = 2).str[-1]
ours['Leap_ID'] = ours.full_name.str.split('_' ).str[0].str[:7]
ours = ours[ours['Leap_ID'].str.contains('Leap0')]
ours.shape

(663, 3)

In [59]:
merge = pd.merge(leor,ours, left_on= ['leap_id','acquisition_raw_id'],right_on= ['Leap_ID','acquisition_ID'],how='inner')
merge.shape

(668, 12)

In [57]:
ours[~ours.full_name.isin(merge.full_name)].sort_

      full_name acquisition_ID  Leap_ID
164  Leap001_14             14  Leap001
412  Leap001_18             18  Leap001
549  Leap001_15             15  Leap001
684  Leap001_19             19  Leap001
717  Leap001_16             16  Leap001
791   Leap010_7              7  Leap010
974  Leap001_17             17  Leap001

In [67]:
leor[leor.leap_id=='Leap010']

,leap_id,run_id,is_core,acquisition_id,acquisition_raw_id,panorama_source_file,panorama_raw_id,large_panorama_raw_id,Unnamed: 8
59,Leap010,NaN,1,001,6,Leap010/raw/Leap010.mcd,3,NaN,NaN
60,Leap010,NaN,1,003,8,Leap010/raw/Leap010.mcd,3,NaN,NaN
61,Leap010,NaN,1,004,9,Leap010/raw/Leap010.mcd,3,NaN,NaN
62,Leap010,NaN,1,005,10,Leap010/raw/Leap010.mcd,3,NaN,NaN
63,Leap010,NaN,1,006,11,Leap010/raw/Leap010.mcd,3,NaN,NaN
64,Leap010,NaN,1,007,12,Leap010/raw/Leap010.mcd,3,NaN,NaN
65,Leap010,NaN,1,008,13,Leap010/raw/Leap010.mcd,3,NaN,NaN

In [66]:
ours[ours.Leap_ID=='Leap010']

      full_name acquisition_ID  Leap_ID
49    Leap010_8              8  Leap010
68   Leap010_12             12  Leap010
105   Leap010_9              9  Leap010
375   Leap010_6              6  Leap010
657  Leap010_10             10  Leap010
734  Leap010_13             13  Leap010
791   Leap010_7              7  Leap010
930  Leap010_11             11  Leap010