In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle as pkl

from scipy.stats import mannwhitneyu

In [2]:
pretreat = pd.read_csv('pretreat_df.csv')

In [3]:
pretreat.columns

Index(['LEAP_ID', 'Biopsy_(Core/Resection)', 'FORCE_cycle',
       'Sample_Type_(pre/post treatment)', 'NACT_Treatment _Group',
       'Response_pCR', 'RCB_Scores', 'RCB_Group', 'Tissue_Format',
       'Extreme_NR', 'FORCE', 'Response', 'Patient_ID', 'Stain_Batch',
       'enrichment_Neutrophil_Monocyte', 'enrichment_CD8_cancerprolif',
       'enrichment_CD4_CD8', 'enrichment_cancer_macroHLA',
       'enrichment_b7h4_cancer'],
      dtype='object')

In [4]:
stat, p = mannwhitneyu(pretreat[pretreat['Response']=='Responder']['enrichment_Neutrophil_Monocyte'],
             pretreat[pretreat['Response']=='Non-Responder']['enrichment_Neutrophil_Monocyte'])

In [5]:
pretreat.columns
# list columns starting with 'enrichment_'
enrichment_columns = [col for col in pretreat.columns if col.startswith('enrichment_')]

In [6]:
enrichment_columns
pretreat_stats = {}
for col in enrichment_columns:
    stat, p = mannwhitneyu(pretreat[pretreat['Response']=='Responder'][col],
                           pretreat[pretreat['Response']=='Non-Responder'][col])
    pretreat_stats[col] = {'statistic': stat, 'p_value': p}

pretreat_stats_df = pd.DataFrame(pretreat_stats).T

In [7]:
pretreat_stats_df

                                statistic   p_value
enrichment_Neutrophil_Monocyte      657.0  0.359154
enrichment_CD8_cancerprolif         333.0  0.002881
enrichment_CD4_CD8                  813.0  0.005123
enrichment_cancer_macroHLA          424.0  0.059806
enrichment_b7h4_cancer              616.0  0.672812

In [8]:
pretreat_stats_df.to_csv('pretreat_stats.csv')

In [9]:
nonresponder = pd.read_csv('nonresponder_df.csv')

In [10]:
enrichment_columns = [col for col in nonresponder.columns if col.startswith('enrichment_')]

In [11]:
nonresponder_stats = {}
for col in enrichment_columns:
    stat, p = mannwhitneyu(nonresponder[nonresponder['Sample_Type_(pre/post treatment)']=='pre'][col],
                           nonresponder[nonresponder['Sample_Type_(pre/post treatment)']=='post'][col])
    nonresponder_stats[col] = {'statistic': stat, 'p_value': p}

nonresponder_stats_df = pd.DataFrame(nonresponder_stats).T

In [12]:
nonresponder.columns

Index(['LEAP_ID', 'Biopsy_(Core/Resection)', 'FORCE_cycle',
       'Sample_Type_(pre/post treatment)', 'NACT_Treatment _Group',
       'Response_pCR', 'RCB_Scores', 'RCB_Group', 'Tissue_Format',
       'Extreme_NR', 'FORCE', 'Response', 'Patient_ID', 'Stain_Batch',
       'enrichment_macro_CD4', 'enrichment_APC_Treg', 'enrichment_mono_BHLA',
       'enrichment_cancerprol_CD8', 'enrichment_macro_fibro'],
      dtype='object')

In [13]:
nonresponder_stats_df

                           statistic   p_value
enrichment_macro_CD4           117.0  0.000561
enrichment_APC_Treg             81.0  0.000027
enrichment_mono_BHLA           293.0  0.851626
enrichment_cancerprol_CD8      380.0  0.046028
enrichment_macro_fibro         205.0  0.105008

In [14]:
nonresponder_stats_df.to_csv('nonresponder_stats.csv')